### PR TITLE
Adds a visual aide for validating your snake

### PR DESCRIPTION
**Pull request by brandonb927**
Activated on-click from the Snakes page, this popover will query the engine and get up-to-date validation for your snake. There is no safeguards to prevent people from spamming this so we might want to visit that in the future.

A Snake with no errors

image

A Snake with lots of errors

image

### CODE REVIEW

**Comment by codeallthethingz** [comment]
scope creepy - but If there is a limit to the number of snakes on a page,
- could we auto make the validate call to each snake on page load
- have the score reflect some kinda colour coding on the `i` ?

**Comment by brandonb927** [comment]
@codeallthethingz `Truly Anything Is Possible™` :)

Currently there is no limit the the number of snakes on this page, though we can enforce a limit. To answer your questions:
1) we could, wouldn't be difficult to do
2) 3/3 == green, anything less == red?

**Comment by codeallthethingz** [comment]
Yeah, i think that either snake is good or not good is the way to go.

**Comment by brandonb927** [comment]
@codeallthethingz something like this?
kapture 2018-10-09 at 20 46 43

**Review by dlsteuer — APPROVED** [review]

**Comment by codeallthethingz** [comment]
ship  it!

**Pull request merged**
