### PR TITLE
Rename models

### PR DESCRIPTION
**Pull request by joram**

### CODE REVIEW

**Comment by brandonb927** [comment]
@joram This looks great, before I approve though I will pull this PR down and give it a thorough test :)

**Comment by dlsteuer** [comment]
Getting a 404 on new tournament:

```

Request Method: | POST
-- | --
http://127.0.0.1:8000/tournament_group/new/
```

looks like it's still trying to go to a tournament_group url @joram

**Comment by joram** [comment]
yeah, I noticed it in https://github.com/battlesnakeio/play/pull/68, but fixed it in that one. I'm half tempted to merge these two together. It would create a bigger pr with the two concepts intertwined. Option B is I go and cherry pick the changes needed to make this branch work, then resolve conflicts in the other branch afterwards. Thoughts?

**Comment by brandonb927** [comment]
@joram I'm fine with you just merging that PR into this one unless, we can sand the rough edges as I test.

**Comment by joram** [comment]
merging other branch (demoed to Daniel)

**Pull request closed without merging**
