### PR TITLE
Add Snakes to Tournaments

### PR DESCRIPTION
**Pull request by tristan-swu**
Some discussion on this PR already happened here:
https://github.com/tristan-swu/play/pull/1

This PR also includes a commit from this branch here (required to let me fix merge conflicts / test)
https://github.com/battlesnakeio/play/pull/84

Adds a new relationship intermediate relationship with foreign keys for:
 - Tournament
 - Snake
 - Bracket

This allows snakes to be added a tournament, and the snakes in the tournament to be added to the bracket(s).

~Todo:~
- ~Tests probably don't pass~
Tests pass!

Resolves: https://github.com/battlesnakeio/roadmap/issues/174
@joram  - this is the work we whiteboarded this week.

### CODE REVIEW

**Comment by codeallthethingz** [comment]
Needs to be rebased from master

**Comment by tristan-swu** [comment]
Rebased. Onto @joram for review.

**Comment by brandonb927** [comment]
@tristan-swu I think there's still some migrations being added here that already exist. Did you pull _then_ rebase?

**Comment by brandonb927** [comment]
Also there seems to be a lot of formatting stuff like converting single quotes to double-quotes, adding spacing around math operators, etc. Is it possible to not have that in this PR so its just the added/deleted code?

**Comment by tristan-swu** [comment]
I'm pretty sure these are net new migrations.

**Comment by brandonb927** [comment]
oops! You are correct. I'm allergic to migrations apparently. Thanks for clearing that up :)

**Comment by joram** [comment]
@brandonb927 or @dlsteuer mind giving this a glance over as well? I think the migrations look good, but wanna make sure the migrations are in a good state post rebase

**Comment by joram** [comment]
tristan and I reviewed the migrations (he knows more than he lets on), zero concerns now.

**Comment by brandonb927** [comment]
I pulled this down and tested it out, and have some comments/questions:
- It looks like editing a bracket no-longer works (returns a 404)
- Teams AND Snakes are now eligible to be in Tournaments? Do I have that right? I ask because of the attached image: one of these snakes is a Team name, and the other is a Snake name. 
image

- If you create a new bracket and add a snake to that bracket that already exists in another bracket, it silently removes from the previous bracket and adds to the new bracket.

**Comment by tristan-swu** [comment]
Ok - for your comments:
 - This looks like an error (bad url) - I just pushed up a commit that fixes it for me
 - Only snakes are added to the tournament (anything in the 'snakes' table). I don't know what url you were on when you took that screenshot, so I can't comment on it.
 - This is currently by design. I talked with John and I understood that to be a rule - one snake per bracket in a tournament. We can design some stuff in the future around notifying people if the snake is already in the bracket.

**Comment by dlsteuer** [comment]
Can we revert the syntax changes though (quote changes etc...), that needs to be through its own pr, it makes it more difficult to see actual changes.

**Comment by tristan-swu** [comment]
Thanks for the feedback. I can understand why you might ask to move styling changes to another pr, but there isn't a formatter or style guide for the project so I don't think anything thats been done in this ps is wrong / incorrect.

Unfortunately I don't have much more free time to contribute. I'm happy to leave this here for anyone that wants to continue with it. Good luck!

**Comment by brandonb927** [comment]
I'll take this and run with it, thanks @tristan-swu

**Pull request closed without merging**
