### PR TITLE
Raw Game Create Form (Roadmap #58)

### PR DESCRIPTION
**Pull request by CDFriend**
Raw HTML form for sending create game requests to the engine. I implemented this thinking that requests to the engine could be sent directly from the browser, but it might be worthwhile to do this through the play server.

The form can be accessed at `http://localhost:8000/create`.

Currently implemented:
* Raw HTML create form (no logic for sending)
* Client-side Javascript for serializing the form into the correct format for a `/create` request to the engine server

### CODE REVIEW

**Comment by joram** [comment]
I think you're right that  it's worthwhile to send the request to the `engine` from the `play` server. We will want to keep track of game history, and a function to start games will be useful for other components of 'play' in the future (leaderboard and testing frameworks come to mind).

**Comment by joram** [comment]
This is functionally better than what `play` does now. I'm happy approving and creating another ticket to move the `engine.create` call to server side, or if you want to do it in this ticket, that would work too. Which would you like to do?

**Comment by CDFriend** [comment]
@joram Given that this ticket is just for the raw form, might be good to make a second for POSTing to the engine?

**Comment by joram** [comment]
then I am happy with this. :+1:

**Pull request merged**
