### PR TITLE
Fix leaderboard migrations

### PR DESCRIPTION
**Pull request by tristan-swu**
Delete and recreated (aka: manually squashed) the migrations in the leaderboard app.

The migrations now correctly apply for both sqlite and postgres databases. 

Fixes: https://github.com/battlesnakeio/roadmap/issues/211

### CODE REVIEW

**Comment by dlsteuer** [comment]
Thanks @tristan-swu

**Comment by brandonb927** [comment]
Isn’t South going to get messed up with this when the migration runs on the next deploy?

**Comment by dlsteuer** [comment]
durr you might be correct

**Comment by brandonb927** [comment]
This is why squashing the migrations is a better fix. We should revert this and do a proper `squashigrations` to satisfy South.

**Comment by brandonb927** [comment]
There is a bunch of leaderboard data right now, but the problem is that in this current state, South is going to complain about missing migrations and fail instantly. From what I understand, squashing migrations is a multi-step deploy sequence:
- Squash the migrations using the django admin tool and commit, merge, and deploy (sets the state of migrations to `0001_squashed`
- Now that South knows about the squashed migrations, you can safely delete the old migrations now that they're no-longer referenced in the migration history

**Comment by tristan-swu** [comment]
Ok - if there's data worth keeping then we're going to have to do a few steps. I attempted the squash migrations command /w this branch but it failed.

1) revert this commit
2) revert the other commit(s) which introduced the migration failure(s)
3) squash migrations
4) Re-apply commits reverted in step 2 - but recreating the migrations

Step 3 might be optional - squashing isn't the only solution - if we fix the busted migrations, then we can skip this step.

That should get us in a good state.

**Pull request merged**
