### PR TITLE
A bunch of workflow fixes and enhancements

### PR DESCRIPTION
**Pull request by brandonb927**
I'll do a demo of this at the next meeting to show the changes

### CODE REVIEW

**Comment by brandonb927** [comment]
@codeallthethingz Fair point! I did add in a confirmation before actually deleting so maybe that will mitigate my original reason of "its too easy to just delete myself from a team"

**Comment by brandonb927** [comment]
@codeallthethingz with that being said, do you think other team members should be able to delete the "team admin" (ie, the team member who creates the team)?

**Comment by codeallthethingz** [comment]
@brandonb927 do we need the concept of team admin at all?  what use cases does it support?

**Comment by brandonb927** [comment]
We had them last year I think? But I'm not sure of the requirements for this year, so I'm open to changing it.

**Pull request merged**
